---
-
  hosts: localhost
  name: Launching an EC2 Instance
  gather_facts: true
  vars:
    keypair: vivek
    instance_type: t2.micro
    security_group: launch-wizard-1
    image: ami-a523b4dd
    region: us-west-2
  tasks:
     - name: Launching an EC2 Instance
       ec2:
           instance_type: "{{ instance_type }}"
           image: "{{ image }}"
           region: "{{ region }}"
           key_name: "{{ keypair }}"
           count: 1
           state: present
           group: "{{ security_group }}"
           wait: true
           vpc_subnet_id: subnet-b97883c0
           assign_public_ip: yes
       register: ec2

